name: Restfull Booker API Automation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Restfull Booker Env.json, qa_env.json]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman & HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Newman Tests
        run: |
          newman run "Restfull Booker Collection.json" \
          -e env/${{ matrix.environment }} \
          -r cli,htmlextra \
          --reporter-htmlextra-export report-${{ matrix.environment }}.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Report-${{ matrix.environment }}
          path: report-${{ matrix.environment }}.html
